description: cnn-painter-adaptive
checkpoint_storage:
  type: shared_fs
  host_path: "/home/chris/checkpoints/painters"

bind_mounts:
  - host_path: "/home/yoavz"
    container_path: "/home/yoavz"

hyperparameters:
  model_type: "original"
  kernel_size: 3
  pool_size: 2
  dropout: 0.5
  l2_reg: 0.003
  lr: 0.000074
  batch_size: 96
  multi_crop: False
  batch_normalization: True

searcher:
  name: single
  metric: roc_auc
  smaller_is_better: true
  max_steps: 300

resources:
  slots_per_trial: 1

min_validation_period: 5
batches_per_step: 744  # 1 epoch

environment:
  runtime_packages:
    - scikit-learn
    - objgraph
    - graphviz
