description: cnn-painter-by-number-entrypoint
checkpoint_storage:
  type: shared_fs
  host_path: "/home/chris/checkpoints/painters"

bind_mounts:
  - host_path: "/home/chris/painters/data_all"
    container_path: "/home/chris/painters/data_all"

hyperparameters:
  kernel_size:
    type: const
    val: 3
  pool_size:
    type: const
    val: 2
  dropout: # original value: 0.5
    type: double
    minval: 0.4
    maxval: 0.6
    count: 3
  l2_reg: # original value: 0.003
    type: double
    minval: 0.002
    maxval: 0.004
    count: 3
  lr: # original value: 0.000074
    type: double
    minval: 0.00007
    maxval: 0.00008
    count: 10

searcher:
  name: grid
  metric: roc_auc
  smaller_is_better: false
  max_steps: 50

max_restarts: 5

resources:
  slots_per_trial: 2

min_validation_period: 10
batches_per_step: 533

environment:
  runtime_packages:
    - scikit-learn
    - objgraph

