description: cnn-painter-by-number-entrypoint
checkpoint_storage:
  type: shared_fs
  host_path: "/home/chris/checkpoints/painters"

bind_mounts:
  - host_path: "/home/chris/painters/data_all"
    container_path: "/home/chris/painters/data_all"
  - host_path: "/tmp"
    container_path: "/tmp"

hyperparameters:
  kernel_size: 3
  pool_size: 2
  dropout: 0.5
  L2_REG: 0.003
  lr: 0.000074
  batch_size: 96

searcher:
  name: single
  metric: roc_auc
  smaller_is_better: false
  max_steps: 621
  source_trial_id: 156

#environment:
#  debug: "0.1.0"


max_restarts: 0

resources:
  slots_per_trial: 2

min_validation_period: 5
batches_per_step: 533

environment:
  runtime_packages:
    - scikit-learn
    - objgraph
  keras: 2.2.4

